### ISSUE TITLE
How do you configure max runs?

### ISSUE THREAD

**Issue by stephencweiss** [mrloop/qunit-retry#8]
It looks like there's support for a "max runs" (i.e. don't retry indefinitely), but I'm unclear how / where you'd configure that since the examples seem to suggest it's a drop in replacement for `test` -- https://github.com/mrloop/qunit-retry/blob/master/src/retry.js#L7

Thanks in advance and thanks for publishing this!

**Comment by mrloop** [comment]
Its not very well documented either in the code or the README and could be improved. The max runs should be 1, unless you pass a third argument to `retry`, with the maxRuns. Going to leave this issue open until the README is updated and code improvement made, probably adding a default value for the maxRuns to make it clear what it is. Feel that maxRuns of 1 is a good default as generally you want to avoid using `retry`. So as drop in replacement it retries once, or you can add a third argument to the retry call and configure the max runs for that test.

**Comment by stephencweiss** [comment]
Gave it a shot with a PR -- but honestly, I'm a little confused if I'm right 😄 . Specifically, maxRuns defaults to 1, but since you start at run 1, wouldn't that mean that for the default there is _no_ retry. You get the initial run and then when the program evaluates whether it should run again, it decides it shouldn't (as `currentRun` will be `2` and `maxRuns` is `1` by default)?

**Comment by mrloop** [comment]
Sorry my mistake the default is maxRuns of 2 see https://github.com/mrloop/qunit-retry/blob/master/main.js#L4-L5 that is retries once.
